name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Run release checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.0"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with: 
          version: 7.14.0
      - name: Install packages
        run: pnpm i
      - name: Create release and publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.N_TOKEN }}
      - name: Update docs site after publish is released
        if: steps.changesets.outputs.published == 'true'
        run: cd packages/vite && pnpm build && cd ../theme-default && pnpm build && cd ../docs-site && pnpm build && node deploy/index.cjs && cd ../docs-site-zh && pnpm build && node deploy/index.cjs
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          ALI_OSS_KEY_ID: ${{ secrets.ALI_OSS_KEY_ID }}
          ALI_OSS_KEY_SECRET: ${{ secrets.ALI_OSS_KEY_SECRET }}
          ALI_OSS_REGION: ${{ secrets.ALI_OSS_REGION }}